# The presence of an empty BUILD makes this folder a package already.

# Use bazel clean to clear the bazel-* directories and start over.
# Do bazel clean --expunge to make extra sure (as sometimes clean doesn't clear it).
